    {% set name = "pandasdmx" %}
{% set version = "1.0.0b2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f79ccd580f74296c204581a5183cabe69a7746912dbc134da726e6c7dd7fbbe8

build:
  number: 0
  noarch: python
  skip: true  # [py<37]  
  script: "{{ PYTHON }} -m pip install . --no-deps -vv" 

requirements:
  host:
    - python
    - pip
    - setuptools >19
  run:
    - lxml >=3.6
    - pandas >=0.24
    - pydantic >=1.1
    - requests >=2.7
    - setuptools >19

test:
  imports:
    - pandasdmx
    - pandasdmx.reader.sdmxml
    - pandasdmx.writer
    
about:
  home: "https://github.com/dr-leo/pandasdmx"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE 
  summary: "A client for SDMX - Statistical Data and Metadata eXchange"
  doc_url: "http://pandasdmx.readthedocs.io/" 
  dev_url: "https://github.com/dr-leo/pandasdmx" 

extra:
  recipe-maintainers:
    - dr-leo
